/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/shibainu/shibainu.glb --output src/components/Shibainu.jsx 
Author: Nyilonelycompany (https://sketchfab.com/Nyilonelycompany)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/shiba-inu-texture-updated-3bb9bc10c8b643c78a94aee15e172f42
Title: Shiba Inu (Texture Updated)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/shibainu.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.025}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Shiba_125" scale={0.01}>
                <group name="skeletal3_124">
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <group name="shiba_inu001_122" />
                    <group name="shiba_inu2_123" />
                    <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Material_0} skeleton={nodes.Object_8.skeleton} />
                    <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} skeleton={nodes.Object_10.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shibainu.glb')
